#! /bin/bash
#SBATCH --job-name=PF_1cond
#SBATCH --output=logs/output_%A_%a.out
#SBATCH --error=logs/error_%A_%a.err

#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=64G
#SBATCH --time=01:00:00
#SBATCH --qos=small

#SBATCH --array=0-9

CONTAINER_URI="docker://dockerhub.moffitt.org/hpc/rocker-rstudio:4.4.2"
BINDS="-B /home/$USER,/share"

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export TZ="US/Eastern"

# ---- hardcode conditions ----
# Order: 5 lines x (hi,lo) = 10
cellLines=("MCF10A" "MDA-MB-231" "SNU668" "SUM-159-chem" "SUM-159-fuse")
#cellLines=("MDA-MB-231")
ploidies=("hi" "lo")

idx=$SLURM_ARRAY_TASK_ID
line_idx=$(( idx / 2 ))
plo_idx=$(( idx % 2 ))

cellLine="${cellLines[$line_idx]}"
ploidy="${ploidies[$plo_idx]}"

MODEL_NAME="model_B1cond"
NUM_THREADS=32
NUM_PATHS=600      # bump as desired
CALC_SIM=1         # consider 0 if you don't need y_sim during PF

echo "Starting task $SLURM_ARRAY_TASK_ID on $(hostname)"
echo "Condition: ${cellLine} ${ploidy}"
echo "Threads: $NUM_THREADS  Paths: $NUM_PATHS  calc_sim: $CALC_SIM"
echo "Container: $CONTAINER_URI"

apptainer exec $BINDS $CONTAINER_URI \
  Rscript MCMC/run_pathfinder_1cond.R "$MODEL_NAME" "$cellLine" "$ploidy" "$NUM_THREADS" "$NUM_PATHS" 
